---
- name: Configure Homelab RHEL 10 Nodes
  hosts: all
  become: true

  tasks:
    - name: Upgrade all system packages # noqa package-latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Install common utility packages
      ansible.builtin.dnf:
        name:
          - vim
          - tmux
          - git
          - bash-completion
          - wget
          - firewalld
          - chrony
        state: present

    - name: Ensure chronyd is running and synced
      ansible.builtin.systemd:
        name: chronyd
        state: started
        enabled: true

    - name: Configure local host resolution mapping
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          172.30.1.200 ansible-control.lab.local ansible-control
          172.30.1.201 web-portfolio.lab.local web-portfolio
          172.30.1.202 media-stream.lab.local media-stream
        marker: "# {mark} ANSIBLE MANAGED HOMELAP MAP"

    - name: Ensure firewalld is running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
