[control]
ansible-control ansible_host=172.30.1.200

[web]
web-portfolio   ansible_host=172.30.1.201

[media]
media-stream    ansible_host=172.30.1.202

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_ed25519