---
- name: Register homelab vms with Red Hat Subscription Manager
  hosts: all
  become: true

  vars_files:
    - vault.yml

  tasks:
    - name: Register system and auto-attach subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ vault_rh_username }}"
        password: "{{ vault_rh_password }}"
        auto_attach: true
